# Generated by Django 5.1.4 on 2024-12-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='name'),
        ),
    ]
