# Generated by Django 5.1.4 on 2024-12-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_phone_number_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='default_username', max_length=255, null=True, verbose_name='Username'),
        ),
    ]
