# Generated by Django 5.1.4 on 2024-12-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertising_image', models.ImageField(upload_to='advertising', verbose_name='изображение рекламы')),
                ('image_link', models.CharField(max_length=255, verbose_name='ссылка рекламы')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Иконка контакта')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
        migrations.CreateModel(
            name='PlatformLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_image', models.ImageField(upload_to='platformLinks', verbose_name='иконка платформы')),
                ('platform_link', models.CharField(max_length=255, verbose_name='ссылка платформы')),
                ('platform_name', models.CharField(max_length=50, verbose_name='название платформы')),
                ('is_socialnetwork', models.BooleanField(default=True, verbose_name='Это социальная сеть?')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформы',
            },
        ),
    ]
