# Generated by Django 5.1.4 on 2024-12-11 04:34

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='NestedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название под-подкатегории')),
            ],
            options={
                'verbose_name': 'Под-подкатегория',
                'verbose_name_plural': 'Под-подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание Товара')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Цена Товара')),
                ('full_desc', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание Товара')),
                ('nestedcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='items.nestedcategory')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='items.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегория',
            },
        ),
        migrations.AddField(
            model_name='nestedcategory',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nested_categories', to='items.subcategory'),
        ),
    ]
